apiVersion: v1
kind: Service
metadata:
  name: svc-site-${NAME}
  labels:
    app: site-${NAME}
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: site-${NAME}
  type: ClusterIP
