apiVersion: v1
kind: Service
metadata:
  name: svc-sftp
  labels:
    app: sftp
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
    nodePort: 30022
  selector:
    app: sftp
  type: LoadBalancer
