apiVersion: v1
kind: Service
metadata:
  name: svc-ldap
  labels:
    app: ldap
spec:
  ports:
  - name: ldap
    port: 389
    protocol: TCP
    targetPort: 389
  selector:
    app: ldap
  type: ClusterIP
