apiVersion: v1
kind: Service
metadata:
  name: svc-registry
  labels:
    app: registry
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  selector:
    app: registry
  type: LoadBalancer
